app = "fly-pb"
primary_region = "sea"

[mounts]
  source = "pb_data" # name of the volume
  destination = "/pb/pb_data"

# optional if you want to change the PocketBase version
[build.args]
  PB_VERSION="0.19.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 500
    hard_limit = 550
